name: Run Script

on:
  workflow_dispatch:
    inputs:
      relo_file:
        description: 'URL to the ReLo file'
        required: true
      fmer_file:
        description: 'URL to the FMER file'
        required: true

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Fetch only the latest commit to reduce checkout time

    - name: Log directory contents before download
      run: ls -la

    - name: Download input files
      run: |
        echo "Downloading ReLo file from ${{ github.event.inputs.relo_file }}"
        curl -L ${{ github.event.inputs.relo_file }} -o relo_df.csv
        echo "Downloading FMER file from ${{ github.event.inputs.fmer_file }}"
        curl -L ${{ github.event.inputs.fmer_file }} -o fmer_df.csv

    - name: Log downloaded files
      run: ls -la

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    - name: Run script
      run: |
        python untitled25.py relo_df.csv fmer_df.csv FleetLite_carts_run_2_${{ github.run_id }}.xlsx

    - name: Log output file
      run: ls -la

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: FleetLite_carts_run_2_${{ github.run_id }}.xlsx
