name: Run Script

on:
  workflow_dispatch:
    inputs:
      relo_file:
        description: 'URL to the ReLo file'
        required: true
      fmer_file:
        description: 'URL to the FMER file'
        required: true

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Fetch only the latest commit to reduce checkout time

    - name: Download input files
      run: |
        curl -L ${{ github.event.inputs.relo_file }} -o relo_df.xlsx
        curl -L ${{ github.event.inputs.fmer_file }} -o fmer_df.xlsx

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    - name: Run script
      run: |
        python untitled25.py relo_df.xlsx fmer_df.xlsx output.xlsx

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: output.xlsx
