name: Run Script

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Fetch only the latest commit to reduce checkout time

    - name: Checkout input files branch
      uses: actions/checkout@v3
      with:
        ref: input-files  # Branch where the input files are stored

    - name: Log directory contents before running script
      run: ls -la

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    - name: Run script
      run: |
        python untitled25.py relo.csv fmer.csv FleetLite_carts_run_2_${{ github.run_id }}.xlsx

    - name: Log directory contents after running script
      run: ls -la

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: FleetLite_carts_run_2_${{ github.run_id }}.xlsx
